name: pnpimagecity
description: "A new Flutter project."
 
 
publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  image_picker: ^1.0.7
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.0.5
  image: ^3.0.1
  image_gallery_saver: ^2.0.3
  remove_bg: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

   
   
   
   
   
  flutter_lints: ^2.0.0

 
 

 
flutter:

   
   
   
  uses-material-design: true

  assets:
    
    - assets/
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
